### ISSUE TITLE
Apps targetting API 30+ can't be installed on device

### ISSUE THREAD

**Issue by grote** [wardvl/f-droid-nightly-action#3]
When trying to install apps targeting API 30 or above, while not using the `--no-resign` option, the apps can not be installed on those Android versions. adb install fails with

```
Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]
```

The action currently relies on an [outdated](https://gitlab.com/fdroid/docker-executable-fdroidserver/-/merge_requests/9) and not maintained docker image which comes with build-tools 26 which probably don't account for the [behavior change in Android 11](https://developer.android.com/about/versions/11/behavior-changes-11#compressed-resource-file).

**Comment by grote** [comment]
If I understand things correctly, `fdroid nightly` puts the key into `$HOME/.android/debug.keystore` and this gets used for signing when building. So for most cases, this issue gets fixed by using the `--no-resign` option. Resigning seems to be just there to ensure that the `DEBUG_KEYSTORE` key gets used.

However, a real fix would probably be to use new build tools (for resigning) which should get pulled in for the app build anyway. I haven't investigated why they don't get used.

**Comment by grote** [comment]
This fixes it: https://github.com/grote/f-droid-nightly-action/commit/5539f9fa29d2a23a0b18f29d40e2f2176af4d18b

@wardvl I forked your repo to test the fix, but don't intent to maintain the fork.

**Comment by eighthave** [comment]
Someone just needs to figure out whether there is any case where `fdroid nightly` needs to strip signatures, then we can just remove that line from _fdroidserver/nightly.py_.  My guess is that signature stripping was only needed when signing with _jarsigner_.

**Comment by grote** [comment]
@eighthave 

```bash
$ apksigner sign --help
USAGE: apksigner sign [options] apk

This signs the provided APK, stripping out any pre-existing signatures.
```

**Comment by eighthave** [comment]
I'll take a look at this, hopefully this week.

Since the original author here is not responding, maybe it makes sense to fork 
this to become an "official" fdroid project?

**Comment by eighthave** [comment]
Hopefully this should fix things: https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1078

**Comment by wardvl** [comment]
@eighthave I'll try it out later this week and see if it fixes things.

**Comment by eighthave** [comment]
@wardvl any luck?

**Comment by grote** [comment]
Still happening. Using 2.1 of this action, it produced this APK: https://github.com/onionshare/onionshare-android-nightly/blob/master/fdroid/repo/org.onionshare.android.nightly_1650639777.apk which can't be installed.

https://github.com/onionshare/onionshare-android/blob/69dd6fb722e43a5f9d289476fdf0203dd5ef039d/.github/workflows/nightly.yml

https://github.com/onionshare/onionshare-android/runs/6130679131?check_suite_focus=true

**Comment by grote** [comment]
My fork of this action was doing `sed -e '/common.apk_strip_v1_signatures/ s/^#*/#/' -i fdroidserver/nightly.py` to fix this. Has this fix been applied to the fdroidserver version used by https://gitlab.com/fdroid/docker-executable-fdroidserver ?

**Comment by grote** [comment]
If I see this correctly, the commit that fixes this in fdroidserver landed 1 day after the release pipeline of the container ran:

* https://gitlab.com/fdroid/fdroidserver/-/commits/master/fdroidserver/nightly.py
* https://gitlab.com/fdroid/docker-executable-fdroidserver/-/jobs/2119735221

@eighthave if that's the case would you mind pressing the re-run button on that `master` pipeline please?

**Comment by grote** [comment]
Thanks for re-running the release pipeline @eighthave. The issue is now finally fixed. Glad it was so easy in the end.
